version: "3"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: petar
      POSTGRES_DB: ads
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5433"
  server:
    platform: linux/amd64
    ports:
      - "3000:3000"
    depends_on:
      - db
    build: ./server
  client:
    networks:
      - app_net
    build: ./client
    ports:
      - "8080:8080"
    depends_on:
      - server

networks:
  app_net:
    driver: bridge
